name: CI

permissions: {}

on:
  pull_request:
  push:
    branches: [syn-serde3]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  ATOMIC_MAYBE_UNINIT_DENY_WARNINGS: 1
  CARGO_HACK_DENY_WARNINGS: 1
  CARGO_LLVM_COV_DENY_WARNINGS: 1
  CARGO_MINIMAL_VERSIONS_DENY_WARNINGS: 1
  CARGO_NO_DEV_DEPS_DENY_WARNINGS: 1
  CONST_FN_DENY_WARNINGS: 1
  PORTABLE_ATOMIC_DENY_WARNINGS: 1
  SEMIHOSTING_DENY_WARNINGS: 1

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  tidy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --no-self-update
          rustup default nightly
      - name: Install cargo-deny and cargo-hack
        run: |
          cargo install cargo-deny --locked
          cargo install cargo-hack --locked
      - run: cat -- tools/.tidy-check-license-headers
      - run: cat -- .cspell.json
      - run: tools/tidy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run cargo-deny
        run: |
          (
            set -x
            cargo hack --workspace-behavior=cargo --no-private --no-dev-deps deny --workspace --all-features check
          )
      - run: git add -N . && git -c color.ui=always diff --exit-code

  check-external-types:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly-2026-06-12
        run: |
          rustup toolchain install nightly-2026-06-12 --no-self-update
          rustup default nightly-2026-06-12
      - name: Install cargo-check-external-types
        run: cargo install cargo-check-external-types --version '=0.5.0' --locked
      - name: Run cargo check-external-types
        run: |
          (
            set -x
            cargo check-external-types --all-features --target=x86_64-unknown-linux-gnu
          )

  clippy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly with clippy
        run: |
          rustup toolchain install nightly --component clippy --no-self-update
          rustup default nightly
      - name: Run cargo clippy
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          bail() {
            printf '::error::%s\n' "$*"
            exit 1
          }
          python3 -m venv ~/venv
          ~/venv/bin/pip --version
          ~/venv/bin/pip install --no-cache-dir --upgrade pip
          ~/venv/bin/pip install --no-cache-dir --uploaded-prior-to=P14D yq
          tomlq() { ~/venv/bin/tomlq "$@"; }
          metadata=$(cargo metadata --format-version=1 --no-deps)
          if [[ -n "${RUSTDOCFLAGS:-}" ]]; then
            printf '%s\n' "+ RUSTDOCFLAGS='${RUSTDOCFLAGS}' \\"
          fi
          export RUSTFLAGS="${RUSTFLAGS} -Z crate-attr=feature(unqualified_local_imports) -D unqualified_local_imports"
          (
            export RUSTFLAGS="${RUSTFLAGS} -Z crate-attr=feature(strict_provenance_lints) -D implicit_provenance_casts"
            printf '%s\n' "+ RUSTFLAGS='${RUSTFLAGS}' \\"
            set -x
            cargo clippy --workspace --all-targets --all-features
          )
          lints=$(tomlq -c 'if .workspace then .workspace.lints else null end' Cargo.toml)
          if [[ "${lints}" == 'null' ]]; then
            lints='{}'
          fi
          clippy_args=(
            -D warnings
          )
          while IFS= read -r; do
            [[ -n "${REPLY}" ]] || continue
            if [[ "${REPLY}" == 'unexpected_cfgs' ]] || [[ "${REPLY}" == 'unexpected-cfgs' ]]; then
              check_cfg="$(jq -c --arg lint "${REPLY}" 'if (.rust[$lint] | type == "object") then .rust[$lint]."check-cfg" else null end' <<<"${lints}")"
              if [[ "${check_cfg}" != 'null' ]] && [[ "${check_cfg}" != '[]' ]]; then
                clippy_args+=(-A "${REPLY}")
                continue
              fi
            fi
            clippy_args+=(-D "${REPLY}")
          done <<<"$(jq -r 'if .rust then .rust | to_entries[] | select((.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | not) | .key else empty end' <<<"${lints}")"
          while IFS= read -r; do
            [[ -n "${REPLY}" ]] || continue
            clippy_args+=(-A "${REPLY}")
          done <<<"$(jq -r 'if .rust then .rust | to_entries[] | select(.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | .key else empty end' <<<"${lints}")"
          while IFS= read -r; do
            [[ -n "${REPLY}" ]] || continue
            clippy_args+=(-D "clippy::${REPLY}")
          done <<<"$(jq -r 'if .clippy then .clippy | to_entries[] | select((.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | not) | .key else empty end' <<<"${lints}")"
          while IFS= read -r; do
            [[ -n "${REPLY}" ]] || continue
            clippy_args+=(-A "clippy::${REPLY}")
          done <<<"$(jq -r 'if .clippy then .clippy | to_entries[] | select(.value == "allow" or ((.value | type == "object") and .value.level == "allow")) | .key else empty end' <<<"${lints}")"
          clippy_args+=(
            -A clippy::semicolon_if_nothing_returned
            -A clippy::used_underscore_items
          )
          IFS=' '
          cat >/tmp/clippy-wrapper.sh <<EOF
          #!/bin/sh
          set -eu
          clippy-driver ${clippy_args[*]} "\$@"
          EOF
          printf '%s\n' "+ cat -- /tmp/clippy-wrapper.sh"
          cat -- /tmp/clippy-wrapper.sh
          chmod +x /tmp/clippy-wrapper.sh
          IFS=$'\n\t'
          export RUSTDOCFLAGS="${RUSTDOCFLAGS:-} -Z unstable-options --no-run --test-builder /tmp/clippy-wrapper.sh"
          printf '%s\n' "+ RUSTDOCFLAGS='${RUSTDOCFLAGS}' \\"
          for manifest_path in $(jq -r '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .targets[].doctest == true) | .manifest_path' <<<"${metadata}"); do
            use_workspace_lints=$(tomlq -c 'if .lints and .lints.workspace then .lints.workspace else false end' "${manifest_path}")
            if [[ "${use_workspace_lints}" != 'true' ]]; then
              bail "'.lints.workspace = true must be set'"
            fi
            (
              set -x
              cargo test --manifest-path "${manifest_path}" --doc --all-features -- --nocapture
            )
          done

  codeql:
    name: codeql (${{ matrix.language }})
    if: github.event_name != 'schedule'
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
            build-mode: none
          - language: rust
            build-mode: none
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --no-self-update
          rustup default nightly
        if: matrix.language == 'rust'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          category: /language:${{ matrix.language }}

  codegen:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --no-self-update
          rustup default nightly
      - run: bash "${SCRIPT}"
        env:
          SCRIPT: tools/gen.sh
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add -N . && git -c color.ui=always diff --exit-code

  docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --no-self-update
          rustup default nightly
      - name: Run cargo rustdoc
        run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          base_args=(
            --lib
            -Z unstable-options
            -Z rustdoc-map
            -Z rustdoc-scrape-examples
            --config "doc.extern-map.registries.crates-io=\"https://docs.rs\""
          )
          base_rustflags=()
          base_rustdocflags=()
          if [[ -n "${RUSTFLAGS:-}" ]]; then
            while IFS= read -rd' '; do
              [[ -z "${REPLY}" ]] || base_rustflags+=("${REPLY}")
            done <<<"${RUSTFLAGS} "
          fi
          if [[ -n "${RUSTDOCFLAGS:-}" ]]; then
            while IFS= read -rd' '; do
              [[ -z "${REPLY}" ]] || base_rustdocflags+=("${REPLY}")
            done <<<"${RUSTDOCFLAGS} "
          fi
          base_rustdocflags+=(
            -Z unstable-options
            --cfg docsrs
            --document-hidden-items
            --document-private-items
            --extern-html-root-takes-precedence
          )
          unset RUSTFLAGS
          unset RUSTDOCFLAGS
          export DOCS_RS=1
          metadata=$(cargo metadata --format-version=1 --no-deps)
          for pkg in $(jq -c '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id and .publish != [])' <<<"${metadata}"); do
            args=("${base_args[@]}")
            pkg_rustflags=("${base_rustflags[@]}")
            pkg_rustdocflags=("${base_rustdocflags[@]}")
            eval "$(jq -r '@sh "MANIFEST_PATH=\(.manifest_path)"' <<<"${pkg}")"
            args+=(--manifest-path "${MANIFEST_PATH}")
            docs_rs_metadata=$(jq '.metadata.docs.rs' <<<"${pkg}")
            if [[ "${docs_rs_metadata}" == "null" ]]; then
              docs_rs_metadata=$(jq '.metadata."docs.rs"' <<<"${pkg}")
              if [[ "${docs_rs_metadata}" == "null" ]]; then
                docs_rs_metadata='{}'
              fi
            fi
            if ! jq '.targets[] | .kind[]' <<<"${pkg}" | grep -Fq '"proc-macro"'; then
              default_target=$(jq -r '."default-target"' <<<"${docs_rs_metadata}")
              if [[ "${default_target}" != null ]]; then
                args+=(--target "${default_target}")
                retry rustup target add "${default_target}" || true
              fi
              if [[ "$(jq '.targets' <<<"${docs_rs_metadata}")" != null ]]; then
                for target in $(jq -r '.targets[]' <<<"${docs_rs_metadata}"); do
                  args+=(--target "${target}")
                  retry rustup target add "${target}" || true
                done
              fi
            fi
            if [[ "$(jq '.features' <<<"${docs_rs_metadata}")" != null ]]; then
              for feature in $(jq -r '.features[]' <<<"${docs_rs_metadata}"); do
                args+=(--features "${feature}")
              done
            fi
            if [[ "$(jq '."all-features"' <<<"${docs_rs_metadata}")" == 'true' ]]; then
              args+=(--all-features)
            fi
            if [[ "$(jq '."no-default-features"' <<<"${docs_rs_metadata}")" == 'true' ]]; then
              args+=(--no-default-features)
            fi
            if [[ "$(jq '."rustc-args"' <<<"${docs_rs_metadata}")" != null ]]; then
              for arg in $(jq -r '."rustc-args"[]' <<<"${docs_rs_metadata}"); do
                pkg_rustflags+=("${arg}")
              done
            fi
            if [[ "$(jq '."rustdoc-args"' <<<"${docs_rs_metadata}")" != null ]]; then
              for arg in $(jq -r '."rustdoc-args"[]' <<<"${docs_rs_metadata}"); do
                pkg_rustdocflags+=("${arg}")
              done
            fi
            if [[ -n "${pkg_rustflags[*]}" ]]; then
              f=''
              for flag in "${pkg_rustflags[@]}"; do
                f+="\"${flag}\","
              done
              args+=(
                --config "build.rustflags=[${f}]"
                -Z host-config
                -Z target-applies-to-host
                --config "host.rustflags=[${f}]"
              )
            fi
            if [[ -n "${pkg_rustdocflags[*]}" ]]; then
              f=''
              for flag in "${pkg_rustdocflags[@]}"; do
                f+="\"${flag}\","
              done
              args+=(
                --config "build.rustdocflags=[${f}]"
              )
            fi
            if [[ "$(jq '."cargo-args"' <<<"${docs_rs_metadata}")" != null ]]; then
              for arg in $(jq -r '."cargo-args"[]' <<<"${docs_rs_metadata}"); do
                args+=("${arg}")
              done
            fi
            (
              set -x
              cargo rustdoc "${args[@]}"
            )
          done

  test:
    needs: [tidy, check-external-types, clippy, codeql, codegen, docs]
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: nightly
            os: windows-latest
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup toolchain install ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Add rust-src component
        run: rustup component add rust-src
        if: startsWith(matrix.rust, 'nightly')
      - name: Install cargo-hack and cargo-minimal-versions
        run: |
          cargo install cargo-hack --locked
          cargo install cargo-minimal-versions --locked
      - name: Install cargo-careful
        run: cargo install cargo-careful --locked
        if: startsWith(matrix.rust, 'nightly')
      - run: cargo test --all --all-features --exclude syn-serde-internal-codegen
      - run: cargo test --all --all-features --release --exclude syn-serde-internal-codegen
      - run: cargo careful test --all --all-features --exclude syn-serde-internal-codegen
        env:
          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -Z randomize-layout
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout
        if: startsWith(matrix.rust, 'nightly')
      - run: cargo hack build --workspace --no-private --feature-powerset --no-dev-deps
      - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features
      - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features --direct

  miri:
    needs: [tidy, check-external-types, clippy, codeql, codegen, docs]
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly with miri
        run: |
          rustup toolchain install nightly --component miri --no-self-update
          rustup default nightly
      - run: printf 'MIRIFLAGS=%s\n' "-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zmiri-disable-isolation -Zmiri-many-seeds=0..16" >>"${GITHUB_ENV}"
        if: github.event_name == 'schedule'
      - run: printf 'MIRIFLAGS=%s\n' "-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zmiri-disable-isolation" >>"${GITHUB_ENV}"
        if: github.event_name != 'schedule'
      - run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          (
            set -x
            cargo miri test --workspace --all-features --exclude syn-serde-internal-codegen
          )
        env:
          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -Z randomize-layout
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout

  msrv:
    name: msrv (${{ matrix.os }})
    needs: [tidy, check-external-types, clippy, codeql, codegen, docs]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-hack
        run: cargo install cargo-hack --locked
      - run: |
          IFS=$'\n\t'
          trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
          args=()
          if [[ "${GITHUB_EVENT_NAME}" == 'pull_request' ]]; then
            args+=(--version-step 2)
          fi
          case "${OS}" in
            ubuntu-*) args+=(--target x86_64-unknown-linux-gnu) ;;
            windows-*) args+=(--target x86_64-pc-windows-msvc) ;;
          esac
          (
            set -x
            cargo hack build --workspace --no-private --no-dev-deps --version-range '..' --all-features "${args[@]}"
          )
        env:
          OS: ${{ matrix.os }}
